server:
  port: 8761

spring:
  application:
    name: eureka-server

# Eureka NO se registra a si mismo: el es el registro
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
